site_name: FastGraphQL
site_description: FastGraphQL is intended to help developer create code driven GraphQL APIs.
site_url: https://hugowschneider.github.io/fastgraphql
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.expand
    - navigation.indexes
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
  language: en
repo_name: hugowschneider/fastgraphql
repo_url: https://github.com/hugowschneider/fastgraphql
edit_uri: ''
docs_dir: pages
plugins:
  - search
  - termynal
  - glightbox
  - gen-files:
      scripts:
        - api-pages.py
  - mkdocstrings:
      watch:
        - ../fastgraphql
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: false
  - literate-nav:
      nav_file: NAV.md
  - section-index
markdown_extensions:
  - admonition
  - tables
  - pymdownx.snippets:
      base_path: 'src/'
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - stylesheets/extra.css
watch:
  - src
  - api-pages.py
nav:
  - FastGraphQL: index.md
  - Tutorial:
    - Getting Started: tutorial/index.md
    - tutorial/data-types.md
    - tutorial/simple-classes.md
    - tutorial/complex-classes.md
    - tutorial/query-mutation.md
    - tutorial/parameters.md
  - Code Reference: api/
